image: node:20

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: 1 hour
  only:
    - main

pages:
  stage: deploy
  needs:
    - job: build
      artifacts: true
  script:
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
  when: manual
  only:
    - main